/* Pixel Trails II — offline input, interface, sound, and local saves. */
(function(){
 'use strict';
 const E=window.PixelEngine,$=id=>document.getElementById(id),canvas=$('world'),dialog=$('dialog'),content=$('dialog-content');
 const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches,KEY='pixel-trails-save-v2';
 const read=key=>{try{return JSON.parse(localStorage.getItem(key)||'null');}catch{return null;}};
 let saved=read(KEY),session=new E.Session(window.PixelRealms.worlds,window.PixelCollisionData,saved,read('pixel-trails-save-v1'));
 let renderer=null,loaded=false,last=0,frameId=0,saveClock=0,hudClock=0,toastTimer=0,bannerTimer=0,previousFocus=null,damageFlash=0,audio=null,storageOK=true;
 let keys=new Set(),touchKeys=new Set(),touchRun=false,attackHeld=false,pointerStart=null,nearestId='',welcomed=!!saved;
 const images={},mini=$('minimap'),mctx=mini.getContext('2d');
 const esc=value=>String(value).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const groups=['npcs','portals','fires','chests','runes','dummies'];
 function save(){try{localStorage.setItem(KEY,JSON.stringify(session.saveData()));storageOK=true;}catch{storageOK=false;}}
 function announce(text){$('live-status').textContent=text;}
 function toast(text){clearTimeout(toastTimer);$('toast').textContent=text;$('toast').hidden=false;announce(text);toastTimer=setTimeout(()=>{$('toast').hidden=true;},3600);}
 function welcome(){if(!welcomed){welcomed=true;$('welcome').hidden=true;}}
 function clearInput(){keys.clear();touchKeys.clear();attackHeld=false;pointerStart=null;session.player.moving=false;document.querySelectorAll('[data-direction]').forEach(b=>b.classList.remove('pressed'));}
 function soundIcon(){const on=session.sound;$('sound-button').setAttribute('aria-pressed',String(on));$('sound-button').setAttribute('aria-label',on?'Turn sound off':'Turn sound on');$('sound-button').title=on?'Sound on':'Sound off';$('sound-icon').innerHTML=on?'<path d="M11 4 6 8H3v8h3l5 4zM16 8c3 2 3 6 0 8M19 4c6 4 6 12 0 16"/>':'<path d="M11 4 6 8H3v8h3l5 4zM16 9l6 6M22 9l-6 6"/>';}
 async function unlockAudio(){if(!session.sound)return;try{const Audio=window.AudioContext||window.webkitAudioContext;if(!Audio)throw new Error('Audio unavailable');if(!audio)audio=new Audio();if(audio.state==='suspended')await audio.resume();}catch{session.sound=false;soundIcon();}}
 function note(freq,duration=.1,delay=0,volume=.025,type='triangle'){if(!session.sound||!audio||audio.state!=='running')return;const at=audio.currentTime+delay,osc=audio.createOscillator(),gain=audio.createGain();osc.type=type;osc.frequency.setValueAtTime(freq,at);gain.gain.setValueAtTime(0,at);gain.gain.linearRampToValueAtTime(volume,at+.01);gain.gain.exponentialRampToValueAtTime(.0001,at+duration);osc.connect(gain);gain.connect(audio.destination);osc.start(at);osc.stop(at+duration+.03);osc.onended=()=>{osc.disconnect();gain.disconnect();};}
 function chime(){[523,659,784,1047].forEach((f,i)=>note(f,.25,i*.08,.03));}
 function action(fn){if(!loaded||dialog.open)return;welcome();unlockAudio();fn();events();updateHud();}
 function events(){let changed=false;for(const e of session.drain()){
  renderer?.effect(e);
  if(e.type==='dialogue')talk(e.npc);
  if(e.type==='win')win();
  if(e.text)toast(e.text);
  if(e.type==='travel'){
   clearInput();renderer.particles=[];renderer.rings=[];renderer.updateCamera(1,true);clearTimeout(bannerTimer);$('realm-title').textContent=session.world.name;$('realm-subtitle').textContent=session.world.subtitle;$('realm-banner').hidden=false;bannerTimer=setTimeout(()=>{$('realm-banner').hidden=true;},2300);chime();
  }
  if(['star','relic','rune','loot'].includes(e.type))chime();
  else if(e.type==='swing')note(155,.065,0,.011,'triangle');
  else if(e.type==='hit'||e.type==='break')note(240,.06,0,.02,'square');
  else if(e.type==='hurt'){damageFlash=.55;note(82,.17,0,.035,'sawtooth');}
  else if(e.type==='heal'||e.type==='camp'){note(660,.2);note(880,.25,.12);}
  else if(e.type==='dash')note(290,.08,0,.01,'sine');
  if(!['swing','hit','dash','enemy-strike','toast'].includes(e.type))changed=true;
 }if(changed)save();}
 function labelFor(o){if(o.kind==='npcs')return o.ending&&session.collected.size===5&&session.relics.size===2?'Restore the beacon':'Talk to '+o.name;if(o.kind==='portals')return o.name;if(o.kind==='fires')return 'Rest & set checkpoint';if(o.kind==='chests')return session.opened.has(o.uid)?'Chest opened':o.sealed?'Open rune cache':'Open treasure chest';if(o.kind==='runes')return session.runes.has(o.uid)?'Rune activated':'Activate rune stone';return 'Training dummy';}
 function updateHud(){const s=session,p=s.player,n=s.collected.size;
  $('health-text').textContent=Math.ceil(p.hp)+' / 100';$('health-fill').style.width=p.hp+'%';$('health-fill').classList.toggle('low',p.hp<30);document.querySelector('.health-track').setAttribute('aria-valuenow',String(Math.ceil(p.hp)));
  $('coin-count').textContent=p.coins;$('potion-count').textContent=p.potions;$('blade-level').textContent='BLADE '+['I','II','III','IV'][p.level];
  $('star-count').textContent=n+' / 5';[...$('stars').children].forEach((a,i)=>{a.classList.toggle('found',i<n);a.textContent=i<n?'✦':'✧';});$('progress-fill').style.width=n/5*100+'%';document.querySelector('.progress-track').setAttribute('aria-valuenow',String(n));
  $('visited-count').textContent=s.visited.size+'/9';$('location-name').textContent=s.world.name;$('rune-count').textContent='RUNES '+s.runeCount()+' / 3';$('minimap-name').textContent=s.world.name.toUpperCase();
  for(const id of ['moonveil','emberfall']){const el=$(id==='moonveil'?'moon-relic':'ember-relic'),yes=s.relics.has(id);el.textContent=(yes?'◆ ':'◇ ')+(id==='moonveil'?'Moonveil':'Emberfall');el.classList.toggle('recovered',yes);}
  $('quest-heading').textContent=s.won?'The light lives on.':n===5&&s.relics.size===2?'Return to Sol.':'Three worlds. One beacon.';
  $('quest-copy').textContent=s.won?'Quest complete. Keep exploring.':n===5&&s.relics.size===2?'Restore the lighthouse in Sunhaven.':'Find five stars and two guardian relics.';
  const near=s.nearest();$('interact-wrap').hidden=!near;
  if(near){$('interact-label').textContent=labelFor(near);if(nearestId!==near.uid){nearestId=near.uid;announce(labelFor(near)+'. Press E.');}}else nearestId='';
  $('dash-button').disabled=p.dashCd>0;$('dash-button').title=p.dashCd>0?'Dash recharging':'Dash (Q)';$('heal-button').disabled=p.potions===0||p.hp===100;
  const boss=s.enemies.find(e=>e.boss&&e.hp>0&&E.distance(e,p)<680);$('boss-hud').hidden=!boss;if(boss){$('boss-name').textContent=boss.name;$('boss-health').style.width=boss.hp/boss.maxHp*100+'%';}
  $('game-state').textContent=JSON.stringify({world:s.worldId,x:Math.round(p.x),y:Math.round(p.y),hp:p.hp,coins:p.coins,potions:p.potions,stars:n,relics:s.relics.size,runes:s.runeCount(),moving:p.moving,route:s.route.length,paused:dialog.open});
 }
 function walkTo(point,object=null){if(!loaded)return;welcome();session.setDestination(point,object);events();canvas.focus({preventScroll:true});}
 function goObject(o){if(E.distance(session.player,o)<82){action(()=>session.interact(o));return;}
  // Interactions stop beside a solid prop, never inside its footprint.
  const target=session.nav.snap(o,p=>E.distance(p,o)<65&&E.distance(p,o)>31);walkTo(target,o);
 }
 function openDialog(eyebrow,html,isMap=false){if(!loaded)return;clearInput();if(!dialog.open)previousFocus=document.activeElement;$('dialog-eyebrow').textContent=eyebrow;content.innerHTML=html;dialog.classList.toggle('map-dialog',isMap);if(!dialog.open)dialog.showModal();dialog.scrollTop=0;content.querySelectorAll('[data-close]').forEach(b=>b.addEventListener('click',closeDialog));updateHud();}
 function closeDialog(){dialog.close();clearInput();previousFocus?.isConnected?previousFocus.focus({preventScroll:true}):canvas.focus({preventScroll:true});updateHud();}
 function talk(npc){welcome();let extra='';if(npc.ending)extra='<div class="help-note">'+(session.won?'The beacon is restored. Thank you, explorer.':`Bring back ${5-session.collected.size} more stars and ${2-session.relics.size} more guardian relics.`)+'</div>';
  if(npc.shop)extra='<div class="shop-grid"><article class="shop-item"><h3>Healing potion</h3><p>Restore 50 health. Carry it anywhere.</p><button class="secondary-button" data-buy="potion">Buy · 15 coins</button></article><article class="shop-item"><h3>Stronger sword</h3><p>+10 damage per swing. Three upgrades available.</p><button class="secondary-button" data-buy="upgrade">Upgrade · 40 coins</button></article></div><p id="shop-wallet" class="subtle"></p>';
  openDialog(npc.role,'<canvas id="portrait" class="portrait" width="68" height="68" aria-hidden="true"></canvas><h2 id="dialog-title">'+esc(npc.name)+'</h2><div class="dialog-copy">'+npc.lines.map(line=>'<p>'+esc(line)+'</p>').join('')+'</div>'+extra+'<div class="dialog-actions"><button class="primary-button" data-close>Back to exploring</button></div>');
  const c=$('portrait').getContext('2d');c.imageSmoothingEnabled=false;window.PixelRenderer.character(c,npc,34,62,3);
  if(npc.shop){const wallet=()=>{$('shop-wallet').textContent=session.player.coins+' coins · '+(30+session.player.level*10)+' sword damage';content.querySelector('[data-buy="upgrade"]').disabled=session.player.level>=3;};wallet();content.querySelectorAll('[data-buy]').forEach(b=>b.addEventListener('click',()=>{session.buy(b.dataset.buy);events();wallet();updateHud();}));}
 }
 function destinations(w){return [...w.portals,...w.fires,...w.npcs,...w.chests.filter(o=>!session.opened.has(o.uid)),...w.runes.filter(o=>!session.runes.has(o.uid))];}
 function bindDestinations(){content.querySelectorAll('[data-go]').forEach(b=>b.addEventListener('click',()=>{const o=groups.flatMap(g=>session.world[g]).find(o=>o.uid===b.dataset.go);if(o){closeDialog();goObject(o);}}));}
 function openMap(id=session.worldId){if(!loaded)return;const w=session.worlds[id],active=id===session.worldId;
  openDialog('ATLAS OF THE THREE WORLDS','<h2 id="dialog-title">'+esc(w.name)+'</h2><div class="world-tabs">'+Object.values(session.worlds).map(a=>'<button data-world="'+a.id+'" class="'+(id===a.id?'active':'')+'" aria-pressed="'+(id===a.id)+'">'+esc(a.name)+'</button>').join('')+'</div><canvas id="full-map" width="1200" height="800" aria-label="'+esc(w.name)+'. '+(active?'Click a path to walk there. Destination buttons follow.':'Enter its portal to travel here.')+'"></canvas><div class="map-legend"><span>● You</span><span>✦ Gold: stars</span><span>● Cyan / orange: portals</span><span>● Red: guardian</span></div><p class="map-note">'+(active?'Click a path, or choose a destination below. You will walk there when this map closes.':'This is a preview. Find its portal in Sunhaven to travel here.')+' The adventure pauses while this panel is open.</p>'+(active?'<div class="map-destinations">'+destinations(w).map(o=>'<button data-go="'+o.uid+'">'+esc(o.name||labelFor(o))+'</button>').join('')+'</div>':'')+'<div class="dialog-actions"><button class="primary-button" data-close>Back to exploring</button><button id="map-journal" class="secondary-button">Journal</button></div>',true);
  const full=$('full-map');renderer.overview(full.getContext('2d'),full.width,full.height,id,true);
  content.querySelectorAll('[data-world]').forEach(b=>b.addEventListener('click',()=>openMap(b.dataset.world)));
  if(active)full.addEventListener('click',e=>{const box=full.getBoundingClientRect(),p={x:(e.clientX-box.left)/box.width*w.width,y:(e.clientY-box.top)/box.height*w.height};closeDialog();walkTo(p);});
  $('map-journal').addEventListener('click',openJournal);bindDestinations();
 }
 function openJournal(){const s=session,stars=s.worlds.sunhaven.stars,hints={lookout:'Climb the old steps in Sunhaven’s northwest.',maker:'Search the path below Dex’s workshop.',dreamer:'Look below the observatory steps, across the river.',story:'Explore the path northeast of the library, beside the river.',kindness:'Follow Rowan’s path toward the beach.'},next=stars.find(a=>!s.collected.has(a.id));
  const rows=stars.map(a=>'<div class="objective-row"><span>'+(s.collected.has(a.id)?'✦':'✧')+' '+esc(a.name)+'</span><span>'+ (s.collected.has(a.id)?'FOUND':'SUNHAVEN')+'</span></div>').join('');
  openDialog('THE EXPLORER’S JOURNAL','<h2 id="dialog-title">A world worth wandering.</h2><p class="dialog-copy">Recover five stars and two guardian relics. Bring them to Sol on Sunhaven’s coast.</p><section class="journal-section"><h3>Island stars · '+s.collected.size+' / 5</h3>'+rows+'</section><section class="journal-section"><h3>Guardian relics · '+s.relics.size+' / 2</h3>'+['moonveil','emberfall'].map(id=>'<div class="objective-row"><span>'+esc(s.worlds[id].enemies.find(e=>e.boss).name)+'</span><span>'+(s.relics.has(id)?'RECOVERED':'UNFOUND')+'</span></div>').join('')+'</section><section class="journal-section"><h3>Rune stones</h3>'+Object.values(s.worlds).map(w=>'<div class="objective-row"><span>'+esc(w.name)+'</span><span>'+s.runeCount(w.id)+' / 3</span></div>').join('')+'</section><div class="help-note"><strong>Your next clue</strong><br>'+esc(next?hints[next.id]:s.relics.size<2?'Enter the blue and red portals. Defeat each world’s guardian in its northeastern arena.':'Visit Sol near the lighthouse to restore the beacon.')+'</div><section class="journal-section"><h3>Places in '+esc(s.world.name)+'</h3><div class="map-destinations">'+destinations(s.world).map(o=>'<button data-go="'+o.uid+'">'+esc(o.name||labelFor(o))+'</button>').join('')+'</div></section><p class="subtle">'+s.opened.size+' chests opened · '+s.destroyed.size+' crates broken · '+s.defeated.size+' creatures defeated</p><div class="dialog-actions"><button class="primary-button" data-close>Keep exploring</button></div>');bindDestinations();
 }
 function openHelp(){openDialog('MAKE YOURSELF AT HOME','<h2 id="dialog-title">Adventure at your pace.</h2><p class="dialog-copy">Explore three worlds, collect five island stars, and defeat two guardians. Find Sol at the lighthouse to finish your adventure.</p><div class="help-list">'+[['Move','W A S D / arrows'],['Run','Shift'],['Swing sword','Space / right-click'],['Dash & briefly evade damage','Q'],['Drink potion · +50 health','H'],['Talk / open / rest / travel','E'],['Map / journal','M / J'],['Pause / close','Esc']].map(([a,b])=>'<div class="help-row"><span>'+a+'</span><span><kbd>'+b+'</kbd></span></div>').join('')+'</div><div class="help-note">Click an open path to walk there, or click an object to approach it. Face a creature before swinging. On touch screens, use the direction pad and action buttons. Enemy warning rings show the attack area: dash out, then strike during recovery.</div><div class="help-note">Campfires fully heal you and set your checkpoint. Each world has a return portal. Activate three runes to unlock its sealed cache. Break crates and fight creatures for coins, then visit Dex to buy supplies.</div><p class="subtle">Progress saves in this browser when local storage is available. Reduced-motion settings are respected. The game pauses in panels and when the tab is hidden.</p><div class="dialog-actions"><button class="primary-button" data-close>Let’s explore</button></div>');}
 function openPause(){save();openDialog('A MOMENT BY THE TRAIL','<h2 id="dialog-title">Take a little breather.</h2><p class="dialog-copy">'+(storageOK?'Your adventure is saved on this device.':'Browser storage is unavailable. Keep this tab open to preserve this session.')+'</p><div class="pause-options"><button class="primary-button" data-close>Resume adventure</button><button id="pause-help" class="secondary-button">How to play</button><button id="pause-map" class="secondary-button">Open world map</button></div><button id="restart" class="danger-button">Start a fresh adventure…</button>');$('pause-help').onclick=openHelp;$('pause-map').onclick=()=>openMap();$('restart').onclick=confirmRestart;}
 function confirmRestart(){openDialog('START AGAIN?','<h2 id="dialog-title">A fresh trail.</h2><p class="dialog-copy">This resets the current game’s stars, relics, treasure and upgrades on this device.</p><div class="dialog-actions"><button class="primary-button" data-close>Keep my adventure</button><button id="confirm-restart" class="secondary-button">Reset adventure</button></div>');$('confirm-restart').onclick=()=>{closeDialog();session=new E.Session(window.PixelRealms.worlds,window.PixelCollisionData);renderer.session=session;renderer.particles=[];renderer.rings=[];renderer.updateCamera(1,true);welcomed=false;$('welcome').hidden=false;damageFlash=0;save();soundIcon();updateHud();toast('A fresh adventure awaits.');};}
 function win(){chime();openDialog('THE BEACON SHINES AGAIN','<div class="win-icon">✦</div><h2 id="dialog-title">You brought back the light.</h2><p class="dialog-copy">Five stars. Two worlds beyond the shore. One brave explorer. Sunhaven’s lighthouse shines again, and every portal is steady.</p><div class="stats"><div class="stat"><strong>3</strong><span>worlds explored</span></div><div class="stat"><strong>'+session.defeated.size+'</strong><span>creatures defeated</span></div><div class="stat"><strong>'+Math.max(1,Math.round(session.seconds/60))+'m</strong><span>on the trail</span></div></div><div class="dialog-actions"><button class="primary-button" data-close>Keep exploring</button></div><p class="subtle">Your quest is complete. Remaining chests, runes and discoveries are still waiting.</p>');}
 function frame(now){const dt=Math.min((now-last)/1000||0,.05);last=now;if(!document.hidden){if(!dialog.open){const x=+(keys.has('d')||keys.has('arrowright')||touchKeys.has('right'))-+(keys.has('a')||keys.has('arrowleft')||touchKeys.has('left')),y=+(keys.has('s')||keys.has('arrowdown')||touchKeys.has('down'))-+(keys.has('w')||keys.has('arrowup')||touchKeys.has('up'));if(x||y)welcome();session.tick(dt,{x,y,run:keys.has('shift')||touchRun,attack:keys.has(' ')||attackHeld});events();renderer.tick(dt);saveClock+=dt;if(saveClock>3){saveClock=0;save();}damageFlash=Math.max(0,damageFlash-dt*2);$('damage-flash').style.opacity=reduced?'0':String(damageFlash);}
  renderer.render();hudClock+=dt;if(hudClock>.12){hudClock=0;updateHud();renderer.overview(mctx,mini.width,mini.height);}}
  frameId=requestAnimationFrame(frame);
 }
 document.addEventListener('keydown',e=>{const k=e.key.toLowerCase();if(!loaded||e.altKey||e.metaKey||e.ctrlKey||dialog.open)return;if(k===' '&&e.target.closest('button,a,input'))return;if(['w','a','s','d','arrowup','arrowdown','arrowleft','arrowright','shift',' ','q','h','e','m','j','escape','f3'].includes(k))e.preventDefault();unlockAudio();if(['w','a','s','d','arrowup','arrowdown','arrowleft','arrowright','shift',' '].includes(k))keys.add(k);if(e.repeat)return;welcome();if(k==='e')action(()=>session.interact());else if(k==='q')action(()=>session.dash());else if(k==='h')action(()=>session.potion());else if(k==='m')openMap();else if(k==='j')openJournal();else if(k==='escape')openPause();else if(k==='?')openHelp();else if(k==='f3')renderer.debug=!renderer.debug;});
 document.addEventListener('keyup',e=>keys.delete(e.key.toLowerCase()));
 canvas.addEventListener('contextmenu',e=>e.preventDefault());
 canvas.addEventListener('pointerdown',e=>{if(!loaded||dialog.open)return;canvas.focus({preventScroll:true});unlockAudio();if(e.button===2){e.preventDefault();const p=renderer.point(e.clientX,e.clientY);attackHeld=true;session.route=[];action(()=>session.attack(p));canvas.setPointerCapture(e.pointerId);return;}if(e.button===0)pointerStart={x:e.clientX,y:e.clientY,id:e.pointerId};});
 canvas.addEventListener('pointerup',e=>{if(e.button===2){attackHeld=false;return;}const start=pointerStart;pointerStart=null;if(!start||start.id!==e.pointerId||Math.hypot(e.clientX-start.x,e.clientY-start.y)>18||dialog.open||!loaded)return;const p=renderer.point(e.clientX,e.clientY),o=groups.flatMap(g=>session.world[g]).find(a=>E.distance({x:a.x,y:a.y-22},p)<34);if(o)goObject(o);else walkTo(p);});
 canvas.addEventListener('pointercancel',clearInput);canvas.addEventListener('lostpointercapture',()=>{attackHeld=false;});
 document.querySelectorAll('[data-direction]').forEach(b=>{const release=()=>{touchKeys.delete(b.dataset.direction);b.classList.remove('pressed');};b.addEventListener('pointerdown',e=>{e.preventDefault();if(!loaded||dialog.open)return;b.setPointerCapture(e.pointerId);touchKeys.add(b.dataset.direction);b.classList.add('pressed');welcome();unlockAudio();});for(const event of ['pointerup','pointercancel','lostpointercapture'])b.addEventListener(event,release);b.addEventListener('click',e=>{if(e.detail===0)action(()=>{const d={up:[0,-12],down:[0,12],left:[-12,0],right:[12,0]}[b.dataset.direction];session.nav.move(session.player,...d);});});});
 $('touch-run').onclick=()=>{touchRun=!touchRun;$('touch-run').setAttribute('aria-pressed',String(touchRun));};
 $('attack-button').addEventListener('pointerdown',e=>{e.preventDefault();if(!loaded||dialog.open)return;e.currentTarget.setPointerCapture(e.pointerId);attackHeld=true;const target=session.enemies.filter(a=>a.hp>0&&E.distance(a,session.player)<140).sort((a,b)=>E.distance(a,session.player)-E.distance(b,session.player))[0];action(()=>session.attack(target));});
 for(const name of ['pointerup','pointercancel','lostpointercapture'])$('attack-button').addEventListener(name,()=>{attackHeld=false;});
 $('attack-button').addEventListener('click',e=>{if(e.detail===0)action(()=>session.attack());});$('dash-button').onclick=()=>action(()=>session.dash());$('heal-button').onclick=()=>action(()=>session.potion());$('interact-button').onclick=()=>action(()=>session.interact());
 $('map-button').onclick=()=>openMap();$('minimap-button').onclick=()=>openMap();$('journal-button').onclick=openJournal;$('help-button').onclick=openHelp;$('pause-button').onclick=openPause;$('dismiss-welcome').onclick=welcome;$('close-dialog').onclick=closeDialog;
 dialog.addEventListener('cancel',e=>{e.preventDefault();closeDialog();});dialog.addEventListener('click',e=>{if(e.target===dialog){const b=dialog.getBoundingClientRect();if(e.clientX<b.left||e.clientX>b.right||e.clientY<b.top||e.clientY>b.bottom)closeDialog();}});
 $('sound-button').onclick=async()=>{session.sound=!session.sound;soundIcon();await unlockAudio();if(session.sound)note(659,.15);save();};
 window.addEventListener('resize',()=>renderer?.resize());window.addEventListener('blur',()=>{clearInput();save();});document.addEventListener('visibilitychange',()=>{if(document.hidden){clearInput();save();}last=performance.now();});window.addEventListener('pagehide',()=>{save();cancelAnimationFrame(frameId);});window.addEventListener('pageshow',e=>{if(e.persisted&&loaded){last=performance.now();frameId=requestAnimationFrame(frame);}});
 Promise.all(Object.values(session.worlds).map(w=>new Promise((resolve,reject)=>{const img=new Image();img.onload=()=>{images[w.id]=img;resolve();};img.onerror=()=>reject(new Error(w.name));img.src=w.image;}))).then(()=>{renderer=new window.PixelRenderer(canvas,session,images,reduced);loaded=true;$('loading').hidden=true;$('welcome').hidden=welcomed;soundIcon();updateHud();renderer.overview(mctx,mini.width,mini.height);last=performance.now();frameId=requestAnimationFrame(frame);}).catch(error=>{$('loading-note').textContent='Could not load '+error.message+'. Extract the whole ZIP and keep the assets folder beside index.html.';});
})();
