"""Rebuild the ground-matched collision grids from the three game maps.

Optional authoring utility: Python + Pillow + NumPy + SciPy.
The shipped game uses collision-data.js directly and has no Python dependency.
The map artwork is read, never modified. Geometry overrides cover stone bridges,
stairs, and solid buildings that cannot be inferred reliably from colour alone.
"""
from pathlib import Path
import json
import numpy as np
from PIL import Image, ImageDraw
from scipy.ndimage import binary_closing, binary_fill_holes, binary_erosion, label

ROOT=Path(__file__).resolve().parents[1]
CELL=4  # image pixels; 8 pixels after the world's 2x geometry transform
OVERRIDES={
 'sunhaven':{
  'image':'island.png','seed':(640,475),
  'floors':[
   [(980,402),(1156,402),(1156,439),(980,439)],
   [(199,50),(229,50),(229,174),(199,174)],
   [(1284,251),(1320,251),(1320,301),(1284,301)],
   [(1278,730),(1300,730),(1300,872),(1278,872)],
  ],
  'blocks':[
   [(329,115),(471,115),(471,266),(329,266)],
   [(720,90),(865,90),(865,227),(720,227)],
   [(587,588),(760,588),(760,713),(587,713)],
   [(1249,64),(1365,64),(1365,238),(1249,238)],
   [(1254,540),(1319,540),(1319,693),(1254,693)],
   [(686,309),(727,316),(761,348),(768,385),(751,414),(711,435),(667,429),(625,405),(616,364),(634,332)],
   [(327,650),(370,650),(376,683),(350,697),(324,684)],
  ]},
 'moonveil':{
  'image':'moonveil.png','seed':(620,475),
  'floors':[
   [(844,291),(976,291),(976,320),(844,320)],
   [(862,683),(1004,683),(1004,713),(862,713)],
   [(151,796),(234,791),(270,815),(280,868),(240,904),(154,895),(125,861),(126,824)],
   [(219,255),(259,245),(266,280),(229,292)],
   [(1419,393),(1469,403),(1455,451),(1411,442)],
   [(70,613),(112,619),(110,668),(63,664)],
  ],'blocks':[]},
 'emberfall':{'image':'emberfall.png','seed':(725,535),'floors':[
  [(873,316),(1014,316),(1014,344),(873,344)],
  [(891,683),(1073,683),(1073,715),(891,715)]
 ],'blocks':[]}
}

def draw_polygons(mask, polygons, value):
 im=Image.fromarray((mask*255).astype('uint8'));d=ImageDraw.Draw(im)
 for p in polygons:d.polygon(p,fill=255 if value else 0)
 return np.array(im)>0

def runs(row):
 result=[];start=None
 for x,v in enumerate(list(row)+[False]):
  if v and start is None:start=x
  elif not v and start is not None:result.extend([start,x-start]);start=None
 return result

def build():
 data={};report=[]
 for key,spec in OVERRIDES.items():
  rgb=np.asarray(Image.open(ROOT/'assets'/spec['image']).convert('RGB')).astype(float)
  r,g,b=rgb[:,:,0],rgb[:,:,1],rgb[:,:,2]
  # The authored maps deliberately use warm sand/stone to distinguish walkable
  # terrain from forest, cliffs, water and lava.
  ground=(r>132)&(g>108)&(b>58)&(r>g*1.035)&(g>b*1.025)&((r-g)<74)&((g-b)<110)
  yy,xx=np.ogrid[-3:4,-3:4];disk=xx*xx+yy*yy<=9
  ground=binary_closing(ground,structure=disk)
  # Close tiny texture holes, never large terrain islands.
  holes=binary_fill_holes(ground)&~ground
  tags,n=label(holes);sizes=np.bincount(tags.ravel());small=sizes<90;small[0]=False
  ground |= small[tags]
  ground=draw_polygons(ground,spec['floors'],True)
  ground=draw_polygons(ground,spec['blocks'],False)
  ground[:10,:]=False;ground[-10:,:]=False;ground[:,:10]=False;ground[:,-10:]=False
  # A cell is ground only if most of its pixels are actually walkable.
  coarse=ground.reshape(256,CELL,384,CELL).mean(axis=(1,3))>.7
  tags,n=label(coarse);sx,sy=spec['seed'];seed=tags[sy//CELL,sx//CELL]
  if not seed:raise ValueError(f'{key}: spawn seed is not ground')
  # Only keep the connected navigable component; isolated rooftops and rocks
  # cannot become accidental destinations.
  coarse &= tags==seed
  data[key]={'cols':384,'rows':256,'cell':8,'rowRuns':[runs(row) for row in coarse]}
  report.append(f'{key}: {int(coarse.sum())} ground cells')
 (ROOT/'collision-data.js').write_text('/* Generated by tools/build-collisions.py. Ground and collision share image coordinates. */\n(function(root){const data='+json.dumps(data,separators=(',',':'))+';if(typeof module!=="undefined"&&module.exports)module.exports=data;else root.PixelCollisionData=data;})(typeof globalThis!=="undefined"?globalThis:this);\n')
 print('\n'.join(report))

if __name__=='__main__':build()
